baseurl = "https://gauthamsk.me/"
languageCode = "en-US"
title = "Gautham Kolluru's"
# Enable comments by entering your Disqus shortname
disqusShortname = "gauthamsk-me"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-63609082-2"
enableRobotsTXT = "true"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  output_13_1 = "output_13_1.png"
  output_40_1 = "output_40_1.png"
  output_41_1 = "output_41_1.png"
  author = "Gautham Kolluru"
  description = "Through the Eyes of Science and the tools of Tech"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "gauthamkolluru"
  Email         = "gautham.kolluru@gmail.com"
  Twitter       = "gauthamkolluru"
  LinkedIn      = "gautamkolluru"
  Stackoverflow = "users/7315848"
  Medium        = ""
  Telegram      = ""
  Mobile        = "+919395345371"

## Main Menu
[[menu.main]]
  name = "if not Tech:"
  weight = 100
  identifier = "Literature"
  url = "/Literature/"
[[menu.main]]
  name = "if Tech:"
  weight = 150
  identifier = "Technology"
  url = "/Technology/"
[[menu.main]]
  name = "Desk-Top"
  identifier = "WorkBench"
  weight = 200
  url = "/WorkBench/"
[[menu.main]]
  name = "repr(myself)"
  identifier = "resume"
  weight = 400
  url = "/Resume.pdf"
[[menu.main]]
  name = "Learn Python"
  identifier = "learnpython"
  weight = 300
  url = "/learnpython/"
[[menu.main]]
  name = "Reach Me"
  identifier = "contact-me"
  weight = 500
  url = "/contact-me/"
